// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: houses/houses.proto

package housespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HousesClient is the client API for Houses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HousesClient interface {
	CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*House, error)
}

type housesClient struct {
	cc grpc.ClientConnInterface
}

func NewHousesClient(cc grpc.ClientConnInterface) HousesClient {
	return &housesClient{cc}
}

func (c *housesClient) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*House, error) {
	out := new(House)
	err := c.cc.Invoke(ctx, "/houses.Houses/CreateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HousesServer is the server API for Houses service.
// All implementations must embed UnimplementedHousesServer
// for forward compatibility
type HousesServer interface {
	CreateHouse(context.Context, *CreateHouseRequest) (*House, error)
	mustEmbedUnimplementedHousesServer()
}

// UnimplementedHousesServer must be embedded to have forward compatible implementations.
type UnimplementedHousesServer struct {
}

func (UnimplementedHousesServer) CreateHouse(context.Context, *CreateHouseRequest) (*House, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouse not implemented")
}
func (UnimplementedHousesServer) mustEmbedUnimplementedHousesServer() {}

// UnsafeHousesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HousesServer will
// result in compilation errors.
type UnsafeHousesServer interface {
	mustEmbedUnimplementedHousesServer()
}

func RegisterHousesServer(s grpc.ServiceRegistrar, srv HousesServer) {
	s.RegisterService(&Houses_ServiceDesc, srv)
}

func _Houses_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HousesServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/houses.Houses/CreateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HousesServer).CreateHouse(ctx, req.(*CreateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Houses_ServiceDesc is the grpc.ServiceDesc for Houses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Houses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "houses.Houses",
	HandlerType: (*HousesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHouse",
			Handler:    _Houses_CreateHouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "houses/houses.proto",
}
