CREATE DATABASE IF NOT EXISTS tuhla;

USE tuhla;

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.houses (
  id INT8 NOT NULL,
  name STRING NULL,
  address STRING NULL,
  create_timestamp TIMESTAMP NULL DEFAULT 'NOW()':::STRING::TIMESTAMP,
  CONSTRAINT houses_pkey PRIMARY KEY (id ASC)
);
